git husky hooks text amends

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,16 +1,11 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-# If everything passes... Now we can commit
-echo 'Trying to build now. 🤔🤔🤔🤔'
-
-npm run build ||
+npm run build || 
 (
-    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
-            Next build or sanity build failed: View the errors above to see why. 
-    '
+    echo '🏗️ 👷 Better call Bob... your build failed. Fix your build and try pushing again
+            Are you seriously trying to write that? Make the changes required above.'
     false;
 )
 
-# If everything passes... Now we can commit
-echo '✅ Pre-push checks passed... have a cookie 🍪 '
+"✅ Build successful - pushing now... oh and... have a cookie! 🍪"
